[package]
name = "peek"
version = "0.1.0"
edition = "2024"

[dependencies]
# pulldown-cmarkとTUIライブラリはそのまま利用
pulldown-cmark = "0.10.0"
ratatui = "0.26.2"
crossterm = "0.27.0"

# パスを正規化するために追加
dunce = "1.0.4"

# ブラウザで開く機能のために追加
opener = "0.6.1"

# クリップボード操作用に追加
arboard = "3.4"
